spring:
    main:
        banner-mode: off
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:mem:testdb;MODE=MYSQL;DATABASE_TO_LOWER=TRUE;
        username: sa
        password:
    h2:
        console:
            enabled: true
            path: /h2-console

#    # JPA Setting
#    jpa:
#        hibernate:
#            ddl-auto: none
#    # SQL Init
#    sql:
#        init:
#            mode: always

    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true
        defer-datasource-initialization: true