spring:
    main:
        banner-mode: off
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:mem:testdb;MODE=MYSQL;DATABASE_TO_LOWER=TRUE;
        username: sa
        password:
    h2:
        console:
            enabled: true
            path: /h2-console

#    # JPA Setting
#    jpa:
#        hibernate:
#            ddl-auto: none
#    # SQL Init
#    sql:
#        init:
#            mode: always

    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true
        defer-datasource-initialization: true

    mail:
        host: smtp.gmail.com
        port: 587
        username: smtp.jinnn99@gmail.com
        password: arhoegaxpytjibkm
        properties:
            mail:
                smtp:
                    starttls:
                        enable: true
                        required: true
                    auth: true
                    connectiontimeout: 5000
                    timeout: 5000
                    writetimeout: 5000