spring:
    main:
        banner-mode: off
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/uracle_kit?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8
        username: root
        password: qwqw1212

#    # JPA Setting
#    jpa:
#        hibernate:
#            ddl-auto: none
#    # SQL Init
#    sql:
#        init:
#            mode: always

    jpa:
        database: mysql
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                show_sql: true
                format_sql: true

    mail:
        host: smtp.gmail.com
        port: 587
        username: smtp.jinnn99@gmail.com
        password: arhoegaxpytjibkm
        properties:
            mail:
                smtp:
                    starttls:
                        enable: true
                        required: true
                    auth: true
                    connectiontimeout: 5000
                    timeout: 5000
                    writetimeout: 5000